version: "1"

services:
  - type: web
    name: voice-agent-backend
    runtime: python
    repo: https://github.com/pgjadhav/AI_Voice_Agent
    plan: free
    region: oregon

    rootDir: app

    buildCommand: pip install -r ../requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000

    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.10.13